refactored part that dependent on localization specific names
AlexFolland/AutoGear pull request #30
Opened 2022-09-03 22:35 UTC by AmsTaFFix

also added definitions to make easier write and read code

2022-09-03 22:35 UTC, AmsTaFFix commented
@AlexFolland

2022-09-05 01:15 UTC, AlexFolland requested changes
Thanks for your pull request!  I'm requesting a few minor changes, and then I'll merge it.

2022-09-05 01:15 UTC, AlexFolland commented on AutoGear.lua
> +					--Alitwin: adding 2hdw
I think we can remove this comment now.

2022-09-05 01:15 UTC, AlexFolland commented on AutoGear.lua
> +		reason = "(classId = " .. itemClassId .. ", it is not usable)"
The `classId` part of this string doesn't match the new variable name.  Please update that to `itemClassId`.

2022-09-05 16:33 UTC, merged